### ISSUE TITLE
Mejora en la clase Fraction

### ISSUE THREAD

**Issue by DavidBlasVazquez** [DavidBlasVazquez/IWVG.SwC.DavidBlas#3]
Incluir el método:
public boolean isProperFraction () Devuelve cierto si es una fracción propia. Falso en cualquier otro caso.
[wiki](https://github.com/DavidBlasVazquez/IWVG.SwC.DavidBlas/wiki).

**Comment by jonh88** [comment]
Buenas!

Issue realizada!

Saludos
